language: python
python:
  - "2.7"
# django environment
env:
  - DJANGO_VERSION=1.6.7
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
#  - pip install PIL --allow-external PIL --allow-unverified PIL
# test
script:
  - cd app
  - python manage.py test

