language: python
python:
  - "2.7"
# django environment
env:
  - DJANGO_VERSION=1.6.7
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install coveralls
# run tests
script:
  cd app
  coverage run --source=django-skeleton manage.py test
after_success:
  coveralls

